# Generated by Django 4.1.3 on 2022-12-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='tht',
            new_name='thoughts',
        ),
    ]
