# Generated by Django 4.1.3 on 2022-12-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniProject', '0003_thought_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thought',
            name='img',
        ),
        migrations.RemoveField(
            model_name='thought',
            name='uid',
        ),
    ]
